import React, { createContext, useContext, useState } from "react";

export type Lang = "en" | "hi" | "gu";

export const translations = {
  en: {
    appName: "RaktCare AI",
    tagline: "SMART BLOOD DONOR ECOSYSTEM",
    dashboardHome: "Dashboard Home",
    donorFinder: "Smart Donor Finder",
    healthPassport: "Donor Health Passport",
    familyVault: "Family Emergency Vault",
    emergencySOS: "Active Emergency SOS",
    compatibility: "Compatibility Graph",
    awareness: "Awareness & Myths",
    analytics: "Diagnostic Analytics",
    assistant: "RaktCare Smart AI",
    findDonor: "Find Donor",
    sosRequest: "SOS Request",
    becomeDonor: "Become Donor",
    learnDonation: "Learn Donation",
    availableDonors: "Available Donors Today",
    clinicalDeficits: "Clinical Deficits",
    bioUnitsSourced: "Bio-Units Sourced",
    activeSOS: "Active SOS",
    emergencySOSList: "Emergency SOS List",
    configureSOS: "Configure SOS",
    compatibilityThresholds: "Compatibility Thresholds",
    exploreGraph: "Explore Graph",
    logEmergency: "LOG EMERGENCY SIGNAL",
    returnSplash: "↑ Return to Splash",
    scrollDashboard: "SCROLL DOWN TO DASHBOARD",
    local: "Local (State)",
    global: "Global (All India)",
    bloodGroup: "Blood Group",
    state: "State",
    city: "City",
    allGroups: "All Groups",
    allCities: "All Cities",
    found: "Found",
    donors: "donors",
    eligible: "Eligible to Donate",
    notEligible: "Not Eligible",
    requestDonor: "Request Donor",
    export: "Export",
    raktScore: "RaktScore",
    hemoglobin: "Hb g/dL",
    weight: "Weight",
    donations: "Donations",
    searchName: "Search name...",
    close: "Close",
    exportPassport: "Export Passport",
    abort: "Abort",
    confirmSourced: "Confirm Sourced",
    page: "Page",
    of: "of",
  },
  hi: {
    appName: "रक्तकेयर AI",
    tagline: "स्मार्ट रक्तदाता पारिस्थितिकी तंत्र",
    dashboardHome: "डैशबोर्ड होम",
    donorFinder: "स्मार्ट डोनर खोजक",
    healthPassport: "डोनर स्वास्थ्य पासपोर्ट",
    familyVault: "पारिवारिक आपातकालीन वॉल्ट",
    emergencySOS: "सक्रिय आपातकालीन SOS",
    compatibility: "संगतता ग्राफ",
    awareness: "जागरूकता और मिथक",
    analytics: "डायग्नोस्टिक एनालिटिक्स",
    assistant: "रक्तकेयर स्मार्ट AI",
    findDonor: "डोनर खोजें",
    sosRequest: "SOS अनुरोध",
    becomeDonor: "डोनर बनें",
    learnDonation: "दान सीखें",
    availableDonors: "आज उपलब्ध डोनर",
    clinicalDeficits: "क्लिनिकल कमी",
    bioUnitsSourced: "बायो-यूनिट प्राप्त",
    activeSOS: "सक्रिय SOS",
    emergencySOSList: "आपातकालीन SOS सूची",
    configureSOS: "SOS कॉन्फ़िगर करें",
    compatibilityThresholds: "संगतता सीमाएं",
    exploreGraph: "ग्राफ देखें",
    logEmergency: "आपातकालीन संकेत दर्ज करें",
    returnSplash: "↑ स्प्लैश पर वापस",
    scrollDashboard: "डैशबोर्ड तक स्क्रॉल करें",
    local: "स्थानीय (राज्य)",
    global: "वैश्विक (पूरा भारत)",
    bloodGroup: "रक्त समूह",
    state: "राज्य",
    city: "शहर",
    allGroups: "सभी समूह",
    allCities: "सभी शहर",
    found: "मिले",
    donors: "डोनर",
    eligible: "दान के योग्य",
    notEligible: "योग्य नहीं",
    requestDonor: "डोनर अनुरोध",
    export: "निर्यात",
    raktScore: "रक्तस्कोर",
    hemoglobin: "Hb g/dL",
    weight: "वजन",
    donations: "दान",
    searchName: "नाम खोजें...",
    close: "बंद करें",
    exportPassport: "पासपोर्ट निर्यात करें",
    abort: "रद्द करें",
    confirmSourced: "स्रोत की पुष्टि करें",
    page: "पृष्ठ",
    of: "का",
  },
  gu: {
    appName: "રક્તકેર AI",
    tagline: "સ્માર્ટ રક્તદાતા ઇકોસિસ્ટમ",
    dashboardHome: "ડેશબોર્ડ હોમ",
    donorFinder: "સ્માર્ટ ડોનર શોધક",
    healthPassport: "ડોનર આરોગ્ય પાસપોર્ટ",
    familyVault: "પારિવારિક કટોકટી વૉલ્ટ",
    emergencySOS: "સક્રિય કટોકટી SOS",
    compatibility: "સુસંગતતા ગ્રાફ",
    awareness: "જાગૃતિ અને દંતકથાઓ",
    analytics: "ડાયગ્નોસ્ટિક એનાલિટિક્સ",
    assistant: "રક્તકેર સ્માર્ટ AI",
    findDonor: "ડોનર શોધો",
    sosRequest: "SOS વિનંતી",
    becomeDonor: "ડોનર બનો",
    learnDonation: "દાન શીખો",
    availableDonors: "આજે ઉપલબ્ધ ડોનર",
    clinicalDeficits: "ક્લિનિકલ ઘટ",
    bioUnitsSourced: "બાયો-યુનિટ મેળવ્યા",
    activeSOS: "સક્રિય SOS",
    emergencySOSList: "કટોકટી SOS યાદી",
    configureSOS: "SOS ગોઠવો",
    compatibilityThresholds: "સુસંગતતા મર્યાદા",
    exploreGraph: "ગ્રાફ જુઓ",
    logEmergency: "કટોકટી સંકેત નોંધો",
    returnSplash: "↑ સ્પ્લેશ પર પાછા",
    scrollDashboard: "ડેશબોર્ડ સુધી સ્ક્રોલ કરો",
    local: "સ્થાનિક (રાજ્ય)",
    global: "વૈશ્વિક (સમગ્ર ભારત)",
    bloodGroup: "રક્ત જૂથ",
    state: "રાજ્ય",
    city: "શહેર",
    allGroups: "બધા જૂથ",
    allCities: "બધા શહેર",
    found: "મળ્યા",
    donors: "ડોનર",
    eligible: "દાન માટે પાત્ર",
    notEligible: "પાત્ર નથી",
    requestDonor: "ડોનર વિનંતી",
    export: "નિકાસ",
    raktScore: "રક્તસ્કોર",
    hemoglobin: "Hb g/dL",
    weight: "વજન",
    donations: "દાન",
    searchName: "નામ શોધો...",
    close: "બંધ કરો",
    exportPassport: "પાસપોર્ટ નિકાસ કરો",
    abort: "રદ કરો",
    confirmSourced: "સ્ત્રોત પુષ્ટિ કરો",
    page: "પૃષ્ઠ",
    of: "નો",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: typeof translations.en;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
